### ISSUE TITLE
Running fips outside any "fipsified" project folder results in an error

### ISSUE THREAD

**Issue by heretique** [floooh/fips#239] opened 2019-10-09 08:29 UTC
Environment: Windows 10, Python 3.7
According to fips documentation, to test if fips works and it is properly installed one needs to "Invoke the fips main script by running ‘./fips’ from within the fips directory". On Windows, run ‘fips’ instead of ‘./fips’.
Doing so it always results in an error:
```
C:\Python37\python.exe: can't find '__main__' module in 'fips
```
even if I run with 'help' argument:
```
fips help
```
This doesn't happen when fips is run from a "fipsified" project. I think some error message should be displayed if fips is being run anywhere else. This seems like an issue.

**Comment by floooh** [comment] 2019-10-09 09:08
Hmm I can't reproduce on Win10 with python 3.7.4, running fips from the fips directory works as expected.

What command shell are you using? I tested with cmd.exe (with ```fips```) and powershell (which requires ```./fips```).

Also can you test the following running ```fips.cmd help``` and ```python fips help```?

Both should do the same thing as running ```fips``` directly (on Windows, this should run the ```fips.cmd``` batch script, which in turn runs python.

**Comment by heretique** [comment] 2019-10-09 09:24
I usually use Cmder on Windows but tested with Command Prompt and Power Shell with the same results:
![Issue Fips cmd](https://user-images.githubusercontent.com/139596/66468933-a4f12200-ea8f-11e9-9123-809cd615771f.png)
![Issue Fips Shell](https://user-images.githubusercontent.com/139596/66468935-a4f12200-ea8f-11e9-91b6-4d20a3436915.png)

**Comment by floooh** [comment] 2019-10-09 09:30
Ah ok... it's a misunderstanding, maybe the wording in the documentation should be better.

You're running ```fips/fips``` from the workspace directory (above the fips directory). I get the same error there.

What I mean with "running from the fips directory" is basically:

```
> cd fips
> fips
```

I'm usually calling that directory where all the project directory and the fips directory itself is in, the "workspace directory", there are no useful actions that can be done from that workspace directory though.

**Comment by heretique** [comment] 2019-10-09 10:54
Ah, I see, thanks for the clarification, it makes a lot of sense now. 
But assuming I have fips in the path for whatever reason, running it in a random folder shouldn't at least show an informative error message, like `"You need to run fips in a "fipsified" project"`?
That python error made me believe at first that fips is broken or I've done something wrong.

**Comment by floooh** [comment] 2019-10-09 11:25
Yes, an error message would make sense. I'm not sure yet if it's possible to do centrally in the fips repository without changing the "frontend" mini-fips-script in actual projects, but I'll write a ticket for that.

**Comment by floooh** [comment] 2019-10-09 11:27
Ok, new bug #240, closing this one :)

**Closed by floooh** 2019-10-09 11:27 UTC
